apiVersion: apps/v1
kind: Deployment
metadata:
  name: goconsomer
spec:
  selector:
    matchLabels:
      app: goconsomer
  template:
    metadata:
      labels:
        app: goconsomer
    spec:
      containers:
        - name: goconsomer
          image: lucas2s/gointensivo:latest
          ports:
            - containerPort: 8080
